apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-rrv
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-rrv
  template:
    metadata:
      labels:
        app: guestbook-ui-rrv
    spec:
      containers:
      - image: quay.io/argoprojlabs/argocd-e2e-container:0.2
        name: guestbook-ui-rrv
        ports:
        - containerPort: 80
